# Tell Mongoid which environment this configuration is for.
production:
  # This starts the session configuration settings. You may have as
  # many sessions as you like, but you must have at least 1 named
  # 'default'.
  sessions:
    # Define the default session.
    default:
      # This configuration is a 3 node replica set.
      hosts:
        - localhost:27017
      database: mongoid
      # We can set session specific options, like reads executing
      # on secondary nodes, and defaulting the session to safe mode.
      options:
        consistency: :eventual
        safe: true

development:
  sessions:
    default:
      database: mongoid
      hosts:
        - localhost:27017